baseURL = 'https://words.vjbe.net/'
locale = 'en-gb'
title = 'Words'
theme = 'quire'

[params]
  author = 'Victor Elgersma-Azmanov'
  email = 'victor@vjbe.net'

[permalinks]
  posts = '/:year/:month/:day/:slug/'
